version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - pgdata:/data/postgres
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@email.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    ports:
      - 15432:80
    depends_on:
      - postgres
    networks:
      - pg-network

  # app:
  #   build: .
  #   container_name: app
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - pg-network

volumes:
  pgdata:
    driver: local

networks:
  pg-network:
    driver: bridge
