version: '3.7'

services:
  database_pg:
    image: ${IMAGE_PG}
    container_name: ${CONTAINER_NAME_PG}
    restart: ${RESTART}
    ports:
      - ${PORTS_PG}
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ${VOLUMES_PG}
    networks:
      - ${NETWORK}

  database_pgadmin:
    image: ${IMAGE_PGADMIN}
    container_name: ${CONTAINER_NAME_PGADMIN}
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@email.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    ports:
      - ${PORTS_PGADMIN}
    depends_on:
      - ${DEPENDS_ON}
    networks:
      - ${NETWORK}

  app:
    build: ${BUILD}
    container_name: ${CONTAINER_NAME_APP}
    ports:
      - ${PORTS_APP}
    volumes:
      - ${VOLUMES_APP}
    networks:
      - ${NETWORK}

volumes:
  pgdata:
    driver: ${DRIVER_VOLUMES}

networks:
  pg-network:
    driver: ${DRIVER_NETWORKS}
